using Avalonia.Media;

namespace VoxScribe.App.Design;

/// <summary>The five themes, in picker order. The first is the default.</summary>
internal static class ThemeCatalog
{
    /// <summary>All themes.</summary>
    public static IReadOnlyList<ThemeDefinition> All { get; } = [Paper(), Orb(), Tide(), Mono(), Fluent()];

    private static ThemeDefinition Paper() => new()
    {
        Id = "paper",
        Label = "Paper",
        Description = "Warm editorial",
        Light = new(0xF4EFE6, 0xFBF8F2, 0xFFFFFF, 0xE3DBCD, 0xEAE2D3, 0x1E1A15, 0x6B6153, 0xFFFFFF,
            PillFill: 0xFFFBF8F2, PillEdge: 0xFFE3DBCD, PillRule: 0xFFD9CFBE),
        Dark = new(0x17130F, 0x211B16, 0x2A231C, 0x3A322A, 0x2C251E, 0xEFE7DA, 0xA89A86, 0x17130F,
            PillFill: 0xFF2A231C, PillEdge: 0xFF3A322A, PillRule: 0xFF4A4036),
        Variants =
        [
            new("plum", "Plum", 0x6A3D9A, 0xC3A4EC),
            new("ink-blue", "Ink blue", 0x2F4C80, 0x9DB6E8),
            new("moss", "Moss", 0x4D6A35, 0xA9C98C),
            new("ochre", "Ochre", 0x8A5A12, 0xE0B062),
        ],
        Display = FontFaces.InstrumentSerif,
        DisplayWeight = FontWeight.Normal,
        Body = FontFaces.Geist,
        Mono = FontFaces.GeistMono,
        StatNumerals = FontFaces.InstrumentSerif,
        StatWeight = FontWeight.Normal,
        HeadlineSize = 48,
        StatSize = 40,
        Headline = null,
        CardRadius = 12,
        ButtonRadius = 999,
        PillRadius = 3,
        Nav = NavStyle.Sidebar,
        NavWidth = 212,
        NavSelection = Selection.Hover,
        TabSelection = Selection.InkFill,
        Stats = StatStyle.Ruled,
        HeroStat = HeroStyle.AccentItalic,
        List = ListStyle.Hairline,
        WordmarkLead = "Vox",
        WordmarkAccent = "scribe",
        WordmarkSize = 30,
        WordmarkAccentItalic = true,
        Pill = PillKind.Paper,
    };

    private static ThemeDefinition Orb() => new()
    {
        Id = "orb",
        Label = "Orb",
        Description = "Luminous dark",
        Light = new(0xEEF0F5, 0xF8F9FC, 0xFFFFFF, 0xDADEE7, 0xE3E6EE, 0x10131A, 0x596070, 0xFFFFFF,
            PillFill: 0xE0FFFFFF, PillEdge: 0x1410131A, PillRule: 0xFFDADEE7),
        Dark = new(0x07080B, 0x0E1015, 0x151821, 0x22262F, 0x1A1E27, 0xE8EAF0, 0x8B91A0, 0x07080B,
            PillFill: 0xEB0E1015, PillEdge: 0x14FFFFFF, PillRule: 0xFF22262F),
        Variants =
        [
            new("nebula", "Nebula", 0x5B3FD6, 0x8C74FF, 0x0E8FA8, 0x5CE1F2),
            new("aurora", "Aurora", 0x0D7C5F, 0x3FE0B0, 0x2F6FD6, 0x7FA8FF),
            new("emerald", "Emerald", 0x127E3E, 0x3DDC84, 0x4E7F12, 0xB8F25C),
            new("ion", "Ion", 0x2350D8, 0x6F92FF, 0x6A36D1, 0xB58CFF),
            new("solar", "Solar", 0xA35A00, 0xFF9F3D, 0x8A6D00, 0xFFE07A),
        ],
        Display = FontFaces.Geist,
        DisplayWeight = FontWeight.SemiBold,
        Body = FontFaces.Geist,
        Mono = FontFaces.GeistMono,
        StatNumerals = FontFaces.GeistMono,
        StatWeight = FontWeight.Medium,
        HeadlineSize = 34,
        StatSize = 30,
        Headline = "Ready when you are.",
        CardRadius = 14,
        ButtonRadius = 10,
        PillRadius = 999,
        Nav = NavStyle.Rail,
        NavWidth = 84,
        NavSelection = Selection.Hover,
        TabSelection = Selection.Hover,
        Stats = StatStyle.Cards,
        HeroStat = HeroStyle.Accent,
        List = ListStyle.Zebra,
        HeaderCard = true,
        Pill = PillKind.Orb,
    };

    private static ThemeDefinition Tide() => new()
    {
        Id = "tide",
        Label = "Tide",
        Description = "Soft and airy",
        Light = new(0xEAF4F8, 0xFFFFFF, 0xFFFFFF, 0xD3E5EE, 0xDCEDF5, 0x0D2433, 0x4D6878, 0xFFFFFF,
            PillFill: 0xFFFFFFFF, PillEdge: 0x00000000, PillRule: 0xFFD3E5EE),
        Dark = new(0x0A1822, 0x122733, 0x16303F, 0x21404F, 0x1A3645, 0xE2F1F8, 0x8FB0C2, 0x0A1822,
            PillFill: 0xFF16303F, PillEdge: 0x00000000, PillRule: 0xFF21404F),
        Variants =
        [
            new("lagoon", "Lagoon", 0x0B6FA0, 0x6CCDF5),
            new("lilac", "Lilac", 0x5F4BC0, 0xB9A9FF),
            new("mint", "Mint", 0x0B7360, 0x6FE3C2),
            new("fern", "Fern", 0x2E7A2E, 0x8EDB7A),
            new("peach", "Peach", 0x9A4E14, 0xFFB27A),
        ],
        Display = FontFaces.Figtree,
        DisplayWeight = FontWeight.ExtraBold,
        Body = FontFaces.Figtree,
        Mono = FontFaces.GeistMono,
        StatNumerals = FontFaces.Figtree,
        StatWeight = FontWeight.ExtraBold,
        HeadlineSize = 36,
        StatSize = 32,
        Headline = null,
        CardRadius = 20,
        ButtonRadius = 999,
        PillRadius = 999,
        Nav = NavStyle.FloatingCard,
        NavWidth = 196,
        NavSelection = Selection.Tint,
        TabSelection = Selection.AccentFill,
        Stats = StatStyle.Cards,
        HeroStat = HeroStyle.Tint,
        List = ListStyle.Card,
        WordmarkLead = "VoxScribe",
        WordmarkSize = 19,
        Pill = PillKind.Tide,
    };

    private static ThemeDefinition Mono() => new()
    {
        Id = "mono",
        Label = "Mono",
        Description = "Terminal brutalist",
        Light = new(0xF2F2EE, 0xFAFAF7, 0xFFFFFF, 0xCFCFC8, 0xE7E7E2, 0x0B0B0B, 0x5C5C58, 0x0B0B0B,
            PillFill: 0xFFFAFAF7, PillEdge: 0xFF0B0B0B, PillRule: 0xFFCFCFC8),
        Dark = new(0x0B0B0B, 0x111111, 0x161616, 0x232323, 0x1C1C1C, 0xF2F2EE, 0x8A8A85, 0x0B0B0B,
            PillFill: 0xFF0B0B0B, PillEdge: 0xFF3A3A3A, PillRule: 0xFF232323),
        Variants =
        [
            new("lime", "Lime", 0x3F6B00, 0xC6FF3D),
            new("phosphor", "Phosphor", 0x0A7A3B, 0x39FF88),
            new("cyan", "Cyan", 0x006B7A, 0x3DF0FF),
            new("violet", "Violet", 0x5A2DB8, 0xB69CFF),
            new("amber", "Amber", 0x8A5200, 0xFFB13D),
        ],
        Display = FontFaces.JetBrainsMono,
        DisplayWeight = FontWeight.ExtraBold,
        Body = FontFaces.JetBrainsMono,
        Mono = FontFaces.JetBrainsMono,
        StatNumerals = FontFaces.JetBrainsMono,
        StatWeight = FontWeight.ExtraBold,
        HeadlineSize = 30,
        StatSize = 32,
        Headline = "> ready_",
        CardRadius = 0,
        ButtonRadius = 0,
        PillRadius = 0,
        Nav = NavStyle.Sidebar,
        NavWidth = 200,
        NavSelection = Selection.AccentFill,
        TabSelection = Selection.InkFill,
        Stats = StatStyle.Ruled,
        HeroStat = HeroStyle.Fill,
        List = ListStyle.Dashed,
        Uppercase = true,
        AccentFillFromDark = true,
        WordmarkLead = "VOX",
        WordmarkAccent = "/",
        WordmarkTail = "SCRIBE",
        WordmarkSize = 15,
        Pill = PillKind.Mono,
    };

    private static ThemeDefinition Fluent() => new()
    {
        Id = "fluent",
        Label = "Fluent",
        Description = "Native Windows 11",
        Light = new(0xEEF0F3, 0xF9F9F9, 0xFFFFFF, 0xE5E5E5, 0xEAEAEA, 0x1B1B1B, 0x5F5F5F, 0xFFFFFF,
            PillFill: 0xFFF9F9F9, PillEdge: 0x0F000000, PillRule: 0xFFE5E5E5),
        Dark = new(0x1F2125, 0x272727, 0x2D2D2D, 0x1C1C1C, 0x2D2D2D, 0xFFFFFF, 0xC5C5C5, 0x000000,
            PillFill: 0xFF2C2C2C, PillEdge: 0x14FFFFFF, PillRule: 0xFF1C1C1C),
        Variants =
        [
            new("system", "Windows blue", 0x005FB8, 0x60CDFF),
            new("teal", "Teal", 0x00777A, 0x4CD9D9),
            new("orchid", "Orchid", 0x8240B3, 0xD3A6FF),
            new("forest", "Forest", 0x107C10, 0x6CCB5F),
        ],
        Display = FontFaces.SegoeDisplay,
        DisplayWeight = FontWeight.SemiBold,
        Body = FontFaces.SegoeText,
        Mono = FontFaces.CascadiaMono,
        StatNumerals = FontFaces.SegoeDisplay,
        StatWeight = FontWeight.SemiBold,
        HeadlineSize = 28,
        StatSize = 28,
        Headline = "Home",
        CardRadius = 8,
        ButtonRadius = 4,
        PillRadius = 8,
        Nav = NavStyle.Sidebar,
        NavWidth = 220,
        NavSelection = Selection.Bar,
        TabSelection = Selection.Underline,
        Stats = StatStyle.Cards,
        HeroStat = HeroStyle.Accent,
        List = ListStyle.Card,
        ContentOnSurface = true,
        Pill = PillKind.Fluent,
    };
}
